/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonSpec`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonStat`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonType`; params?: Router.UnknownInputParams; } | { pathname: `/components/Radio`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/SortButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Shadows`; params?: Router.UnknownInputParams; } | { pathname: `/functions/pokemon`; params?: Router.UnknownInputParams; } | { pathname: `/functions/utils`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFetchQuery`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColors`; params?: Router.UnknownInputParams; } | { pathname: `/pokemon/PokemonCard`; params?: Router.UnknownInputParams; } | { pathname: `/pokemon/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PokemonSpec`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PokemonStat`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PokemonType`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Radio`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SortButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/Shadows`; params?: Router.UnknownOutputParams; } | { pathname: `/functions/pokemon`; params?: Router.UnknownOutputParams; } | { pathname: `/functions/utils`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useFetchQuery`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useThemeColors`; params?: Router.UnknownOutputParams; } | { pathname: `/pokemon/PokemonCard`; params?: Router.UnknownOutputParams; } | { pathname: `/pokemon/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Card${`?${string}` | `#${string}` | ''}` | `/components/PokemonSpec${`?${string}` | `#${string}` | ''}` | `/components/PokemonStat${`?${string}` | `#${string}` | ''}` | `/components/PokemonType${`?${string}` | `#${string}` | ''}` | `/components/Radio${`?${string}` | `#${string}` | ''}` | `/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/components/SortButton${`?${string}` | `#${string}` | ''}` | `/components/ThemedText${`?${string}` | `#${string}` | ''}` | `/constants/Colors${`?${string}` | `#${string}` | ''}` | `/constants/Shadows${`?${string}` | `#${string}` | ''}` | `/functions/pokemon${`?${string}` | `#${string}` | ''}` | `/functions/utils${`?${string}` | `#${string}` | ''}` | `/hooks/useFetchQuery${`?${string}` | `#${string}` | ''}` | `/hooks/useThemeColors${`?${string}` | `#${string}` | ''}` | `/pokemon/PokemonCard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonSpec`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonStat`; params?: Router.UnknownInputParams; } | { pathname: `/components/PokemonType`; params?: Router.UnknownInputParams; } | { pathname: `/components/Radio`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/SortButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Shadows`; params?: Router.UnknownInputParams; } | { pathname: `/functions/pokemon`; params?: Router.UnknownInputParams; } | { pathname: `/functions/utils`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFetchQuery`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColors`; params?: Router.UnknownInputParams; } | { pathname: `/pokemon/PokemonCard`; params?: Router.UnknownInputParams; } | `/pokemon/${Router.SingleRoutePart<T>}` | { pathname: `/pokemon/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
